(======INFO=====================)
(G00 – Rapid Positioning)
(G01 – Linear Interpolation)
(G02 – Circular Interpolation Clockwise)
(G03 – Circular Interpolation Counterclockwise)
(S1000	    (---LaserOn 100% ON)       )
(S0 		(---LaserOff 000% OFF)     )
(M30 – End of program)
(======START=====================)
(REPLACE .000000 ; )
(REPLACE F0 ; F1000  or F750 )
(REPLACE G0 X ; G0 F1000 X )
(REPLACE G1 X ; G0 F750 X )
(REPLACE G2 X ; G0 F750 X )
(REPLACE G3 X ; G0 F750 X )
(======CODE MANDATORY============)
M3 S0  (M03 – Spindle on in a clockwise)
(================================)
(=BEGIN Engrave=========================)


(=END Engrave===========================)
(======END============)
S0 (---Laser 00% OFF)
G0 Z10.000000
(======END============)
